# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70f5ce4e5d0a8c776d4588e6efc3056f8a7f653973c7ffaa5804a003f27207f812ebbd77e6a68eaa8f222508014faecaf2562c111a6667906d68205a6fcb224

test:
  secret_key_base: a8ea1c724c50dc7a24c409198ae1cbc980ed4a68878fcc422aae89ea235d18fa935fa57b4f2191ec3d67cad2ecf1da09196827849f7133b14fc2333b97c2baf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
